# Generated by Django 6.0.2 on 2026-02-28 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=150)),
                ("address_number", models.IntegerField()),
                ("tel", models.BigIntegerField()),
                ("document", models.BigIntegerField()),
                (
                    "born_year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2026),
                        ]
                    ),
                ),
            ],
        ),
    ]
