# Generated by Django 6.0.2 on 2026-03-02 14:09

import django.db.models.deletion
import order.models.rental_model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0001_initial"),
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rental_day", models.DateTimeField(auto_now_add=True)),
                (
                    "return_day",
                    models.DateTimeField(
                        default=order.models.rental_model.default_return_day
                    ),
                ),
                ("returned", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.customer",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movie.movie"
                    ),
                ),
            ],
        ),
    ]
